services:
  - type: web
    name: healthbridge
    runtime: python3
    disk:
      name: healthbridge-data
      mountPath: /var/data
      sizeGB: 1
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput --clear
    startCommand: python manage.py migrate --noinput && python manage.py create_render_superuser && gunicorn healthcare.wsgi:application --bind 0.0.0.0:$PORT --log-level info
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: healthcare.settings
      - key: SECRET_KEY
        value: uq9id1Da-oSGt1IWwOHEncy4C6_VJkINFF5Hl67ma8DyjU-oCOXRzyDh8BRzBp6T5L4
      - key: DEBUG
        value: "False"
      - key: RENDER
        value: "1"
      - key: DJANGO_SUPERUSER_USERNAME
        value: anshika
      - key: DJANGO_SUPERUSER_EMAIL
        value: anshika@gmail.com
      - key: DJANGO_SUPERUSER_PASSWORD
        value: anshika
