services:
  - type: web
    name: healthbridge
    runtime: python3
    buildCommand: pip install -r requirements.txt && python manage.py migrate --noinput && echo "Migrations applied successfully" && python manage.py collectstatic --noinput
    startCommand: mkdir -p /var/data && gunicorn healthcare.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: healthcare.settings
      - key: SECRET_KEY
        value: uq9id1Da-oSGt1IWwOHEncy4C6_VJkINFF5Hl67ma8DyjU-oCOXRzyDh8BRzBp6T5L4
      - key: DEBUG
        value: "False"
      - key: RENDER
        value: "1"
      - key: DB_PATH
        value: /tmp/db.sqlite3
      - key: DJANGO_SUPERUSER_USERNAME
        value: admin
      - key: DJANGO_SUPERUSER_EMAIL
        value: admin@healthbridge.com
      - key: DJANGO_SUPERUSER_PASSWORD
        value: admin123
